### ISSUE TITLE
Unable to export on mashup

### ISSUE THREAD

**Issue by skippertabs** [stefanwalther/sense-export#11]
We are using this export widget on our public mashup but the QAP security is blocking the export functionality.

**Comment by wikolaw** [comment]
We also have the same problem. @skippertabs , have you found any workaround? 

Regards,

Wiko

**Comment by skippertabs** [comment]
No, but we ended up making our own extension.

**Comment by wikolaw** [comment]
Hello Thabi,

Is that something you can share with us?

Regards,

Wiko

**Comment by stefanwalther** [comment]
Have a look at the newest version of this extension (v1.2.2), where I have added a client side export which also works in case you have a Virtual Proxy set up for anonymous access.

Quote from the README:

![image](https://cloud.githubusercontent.com/assets/669728/25879425/ef86e180-3531-11e7-91d1-ab67d007c37a.png)

Hope this works.
Closing this issue, pls feel free to re-open if this doesn't solve your problem.
