### ISSUE TITLE
wbfolder.wbl file missing

### ISSUE THREAD

**Issue by ltrowski** [stefanwalther/sense-export#15]
Hello,

in version 3.0.0 of Sense I cannot use the extension, the error in Sense Desktop is that the wblfolder.wbl file is missing (in dev-hub). I tried to write one on my own but it still does not work. Also on Sense Server 3.0.0 I cannot upload the extension getting the error of a duplication...? I think the reason should be the same. The Qlik Support also mentioned that the format of the swr-sense-export.qext looks quite old.
![error](https://cloud.githubusercontent.com/assets/26252989/23661135/090a52f8-034c-11e7-967c-1e8b6141ea5b.pNG)

KR
Lukas

**Comment by ltrowski** [comment]
Any news?

**Comment by stefanwalther** [comment]
See db4cde4

**Comment by stefanwalther** [comment]
Closed with db4cde4

The default build of sense-export minifies the JavaScript files and does not contain a `wbfolder.wbl` file (which is just necessary for Dev Hub). 

So if you want to edit the extension or create your own extension based on sense-export download the [./build/sense-export_dev.zip](https://github.com/stefanwalther/sense-export/raw/master/build/sense-export_dev.zip) file which always contains the latest version + a `wbfolder.wbl` file.
