### ISSUE TITLE
Export Definition: Semicolon Separated CSV

### ISSUE THREAD

**Issue by mruehl** [stefanwalther/sense-export#16]
I would really appreciate an export definition "Semicolon Separated CSV".
I can't edit the extension by myself because of the missing wbl-file.

**Comment by stefanwalther** [comment]
As I am using the methods being provide by the QIX Engine, I unfortunately have to tell you that this is not possible.

But in the newest release (v1.2.2) I have also created a client-side export, where you could change the delimiter.
