### ISSUE TITLE
Sense Export Button for  Anonymous Users not downloading all the rows

### ISSUE THREAD

**Issue by Qlik-MN** [stefanwalther/sense-export#25]
### Description
We are seeing a weird issue when using Sense Export Button for Anonymous users. The total number of rows downloaded in the csv file is being capped to 500 rows when the number of rows in the table component is between 500 to 1500 rows. When the number of rows is greater than 1500 then the downloaded csv file contains about 99% of the rows but does not match completely.

If I login as a registered user and use this button then the number of rows downloaded in csv will match exactly irrespective of the row count.

Sense Export Button for Anonymous Users
Under properties panel : Export Definition: 'Comma Separated CSV - Client side'
Logged in as Anonymous User:
Selected a Product 1
Vertical Table Displayed 300 records. 
Clicked 'Sense Export' button - exported file showed exactly 300 rows
Selected a Product 2
Table displayed 630 records.
Clicked 'Sense Export' button - exported file showed only 500 rows.
Selected  Product 3
Table displayed 60610 records.
Clicked 'Sense Export' button - exported file showed only 60605 rows.
##### Operating system
[ ] Windows 7 Enterprise
##### Qlik Sense
[ ] Enterprise
##### Browser
[ ] Internet Explorer
### Versions

* Browser: IE11
* Qlik Sense: 3.2 SR4
* Operating system: Windows

**Comment by stefanwalther** [comment]
I was just trying to reproduce the issue, but can't ... is it possible that you send me your application? (Just send it to swrnixda at gmail dot com)

**Comment by Qlik-MN** [comment]
Hi Stefan,

We will send you the application asap. Thank You!!!


Manaswini Narala
FAERS Project
CNI Global Solutions, LLC,
301-354-5168 (off)

**Comment by stefanwalther** [comment]
Thx for sending me the files. Fixed in version 1.2.5 of sense-export.
