### ISSUE TITLE
Most recent version is missing reference to Filesaver.JS 

### ISSUE THREAD

**Issue by pwharris8** [stefanwalther/sense-export#27]
### Description

[Description of the issue]

### Steps to Reproduce

1. Download the latest version of sense-export
2. Import extension to Qlik Sense server
3. Configure export button for client side csv

##### Expected behavior

file downloads on the client side

##### Actual behavior

reference error : saveAs() not defined. I added a reference to external/file-saver/FileSaver.min in the swr-sense-export file and it resolved the issue. 

##### Operating system
```
[x ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x ] Enterprise
```

##### Browser

```
[ x] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Browser: 
* Qlik Sense: 3.2 SR4
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Yes, you are right, thx for reporting, I'll provide a fix ASAP.

**Comment by pwharris8** [comment]
Thanks Stefan! Great extension.
