### ISSUE TITLE
Large data export truncated

### ISSUE THREAD

**Issue by fergus040** [stefanwalther/sense-export#4]
First off- love this extension any many of your other great extensions.

Issue I am experiencing is o  sense 2.1.1 and occurs when I try to export a dataset with 15 columns and about 80,000 rows.  

The number of rows is truncated to 66501 Flanders I do not know why

**Comment by stefanwalther** [comment]
This is a limitation of Excel ([see here](https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)).

But there is a solution:
Using the [newest version v1.0.2 of this extension](https://github.com/stefanwalther/sense-export/blob/master/build/sense-export_v1.0.2.zip) just set the download format to .csv and all your data will be downloaded. Just tested it with 2mio records, works.

**Comment by stefanwalther** [comment]
Cleaning up and closing. Feel free to re-open if your issue isn't solved with the newest version.

**Comment by bxlxux** [comment]
Hello - love the utility of this. Somewhat opposite to the above, the csv I export will pull 260K rows and the excel file the full 500+ thousand rows. Any thoughts?

**Comment by stefanwalther** [comment]
@bxlxux, sorry, no ideas.
