### ISSUE TITLE
Export will only download Excel format 

### ISSUE THREAD

**Issue by fergus040** [stefanwalther/sense-export#5]
Despite selecting csv from the settings, the extension only exports Xlsx.  Using sense 2.1.1

**Comment by dyhessyca** [comment]
Hi Stefan, the extension doesn't export csv.
Using Sense 2.2.4

**Comment by stefanwalther** [comment]
OK, thx for reporting, I'll have a look ...

**Comment by dyhessyca** [comment]
Hi Stefan
I am with same problem.
Using Sense 2.2.4
Export only excel
I need to export csv.

Tks

2016-06-09 15:17 GMT-03:00 Stefan Walther <notifications@github.com>:

> OK, thx for reporting, I'll have a look ...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/stefanwalther/sense-export/issues/5#issuecomment-224981494>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS63a7eH0ZrVpkp6g3XQry1gHUMzZ2lIks5qKFikgaJpZM4Idgbe>
> .
>



-- 





* <dyhessyca@yahoo.com.br>Dyhessyca Correa Cockpit de Gestão 41 84755933
(oi)dEle, por Ele, para Ele.{Pensada pelo amor. Gerada pelo Espírito.
Escondida nos braços do Autor da vida.}*

**Comment by stefanwalther** [comment]
OK, fixed it, pls have a look at the new version v1.0.1.
