### ISSUE TITLE
akquinet sense excel issue

### ISSUE THREAD

**Issue by nancysbeity** [stefanwalther/sense-export#6]
Hello,
I downloaded the sense excel extension lately. I have all the requirements installed and verified, but:
- When I install the akquinet-sense-excel-2.1.2.46.xll the Qlik Sense tab appears. But, I don't have a connection String "Qlik Sense Desktop" and when I add the Server URL it doesn't work.
- Also, after adding AutoLoad tick as mentioned in the instruction pdf, we I reopen Excel, the Qlik Sense tab doesn't appear.

Thank you for your help!
Nancy Sbeity

**Comment by stefanwalther** [comment]
Sorry, don't get how this is related to sense-export?

**Comment by nancysbeity** [comment]
Oh, Sorryy! It's a wrong conversation!

**Comment by stefanwalther** [comment]
OK, thx, therefore I close it.
