### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by DigitalrepNB** [stefanwalther/sense-export#8]
Hello,

I'm having an issue importing the extension in version 2.2.4 "Server, not Desktop" I'm logged on as the administrator with all the security roles. When I go to import it errors our right away. I can see a folder was created "swr-sense-export" I have deleted the file and retried the import again. 

![image](https://cloud.githubusercontent.com/assets/7997573/17709500/2fc42a02-639e-11e6-90dc-233440d607cc.png)

We are looking to add the option to export to .csv

Thanks
Nathan

**Comment by tension83** [comment]
Hello,

i have the same error whit sense-export-master
![sense-export-master](https://cloud.githubusercontent.com/assets/7509687/23299563/a2db6054-fa8a-11e6-87b0-141b2ef3f24e.png)


Best regards,
Stefan

**Comment by stefanwalther** [comment]
Please make sure that you don't download the entire GitHub repo, but the builds I have provided in the `./buid` directory. This should solve your issue:

![image](https://cloud.githubusercontent.com/assets/669728/25879338/6901cf30-3531-11e7-809f-c41fdf45e17b.png)
