### ISSUE TITLE
Export in Firefox 

### ISSUE THREAD

**Issue by edettrey** [stefanwalther/sense-export#9]
When attempting to use this button in firefox, a "Connection lost" error is thrown
It totally locks up the application.
It will still generate the excel worksheet. 

Works fine in Chrome

Environment: 
QlikSense Server (3.0.1)
Embedded via single configurator into our flagship application. 

Any ideas?

**Comment by stefanwalther** [comment]
As I cannot reproduce this issue with FireFox I am closing this issue. Please feel free to re-open if you are still experiencing the issue with the newest version of sense-export.
